### PR TITLE
Feature/issue 47 aws iam certificate

### PR DESCRIPTION
**Pull request by imacube**
Adds support for certificates stored in IAM for issue #47

### CODE REVIEW

**Comment by joshrosso** [comment]
Thanks @imacube, going to take a look at this later today.

File: awsutil/iam.go [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+  "github.com/aws/aws-sdk-go/aws"
+  "github.com/aws/aws-sdk-go/aws/request"
+  "github.com/aws/aws-sdk-go/service/iam"
+  "github.com/aws/aws-sdk-go/service/iam/iamiface"
+  "github.com/aws/aws-sdk-go/aws/session"
+  "github.com/golang/glog"
+  "github.com/prometheus/client_golang/prometheus"
+)
+
+// ACM is our extension to AWS's ACM.acm
```
Comment (joshrosso) [inline awsutil/iam.go]: `ACM` -> `IAM`.

File: awsutil/iam.go [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+		}
+	})
+
+	iamClient := IAM{
+		iam.New(awsSession),
+	}
+	return &iamClient
+}
+
+// CertExists checks whether the provided ARN existing in AWS.
```
Comment (joshrosso) [inline awsutil/iam.go]: `existing` -> `exists`.

File: awsutil/iam.go [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+func (i *IAM) CertExists(arn *string) bool {
+  arn_string := *arn
+  certificate_name := arn_string[strings.LastIndex(arn_string, "/") + 1:len(arn_string)]
```
Comment (joshrosso) [inline awsutil/iam.go]: Switch vars to mixed case or shorter vars rather than using `_`: https://golang.org/doc/effective_go.html#mixed-caps

e.g. `arn_string` -> `a` ... `certificate_name` -> `c`

**Comment by imacube** [comment]
@joshrosso No problem. I shouldn't have missed the ACM lines and I'm still getting used to go's variable name formatting.

File: awsutil/iam.go [hunk 4]
```diff
@@ -0,0 +1,53 @@
+package awsutil
+
+import (
+  "strings"
+
+  "github.com/aws/aws-sdk-go/aws"
+  "github.com/aws/aws-sdk-go/aws/request"
```
Comment (philips) [inline awsutil/iam.go]: please run go fmt over the file.

**Comment by joshrosso** [comment]
@imacube, just fyi I haven't forgot about this.

Just haven't had the cycles yet to test it out. I will as soon as possible and get back to you.

Thanks for the quick fixes based on comments!

**Comment by joshrosso** [comment]
@imacube Sorry for the crazy delay.

Really hoping to merge this today.

The [glide.yaml](https://github.com/coreos/alb-ingress-controller/blob/master/glide.yaml#L18-L31) needs to be updated to include IAM, subsequently we also need the `glide.lock`, and `vendor/` re-committed once upgraded.

**Comment by joshrosso** [comment]
@imacube, thanks!

**Comment by imacube** [comment]
@joshrosso I'm seeing a build error I've not encountered before, go wants `github.com/spf13/pflag` from within `vendor/k8s.io/ingress/vendor/github.com/spf13/pflag`, but `github.comspf13/pflag` still exists in `vendor/github.com/spf13/pflag`. Not sure how to fix this.

```
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOARM=6 go build -a -installsuffix cgo -ldflags '-w' -o server ./main.go
# github.com/coreos/alb-ingress-controller/controller
controller/controller.go:43: cannot convert ac (type *ALBController) to type ingress.Controller:
	*ALBController does not implement ingress.Controller (wrong type for OverrideFlags method)
		have OverrideFlags(*"github.com/coreos/alb-ingress-controller/vendor/github.com/spf13/pflag".FlagSet)
		want OverrideFlags(*"github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/vendor/github.com/spf13/pflag".FlagSet)
controller/controller.go:43: impossible type assertion:
	*ALBController does not implement ingress.Controller (wrong type for OverrideFlags method)
		have OverrideFlags(*"github.com/coreos/alb-ingress-controller/vendor/github.com/spf13/pflag".FlagSet)
		want OverrideFlags(*"github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/vendor/github.com/spf13/pflag".FlagSet)
make: *** [server] Error 2
```

**Comment by joshrosso** [comment]
@imacube, if you flatten the dependencies using `-v`  with `glide` `install` / `update` it'll flatten the vendoring, which appears to be the root issue.

http://glide.readthedocs.io/en/latest/commands/#glide-update-aliased-to-up

Let me know if this helps.

**Comment by imacube** [comment]
@joshrosso Thanks! The `-v` fixed the problem.

**Comment by joshrosso** [comment]
Brought up to date with `rebase` so IAM code shares aws session introduced in #99.

**Comment by joshrosso** [comment]
@imacube Great work and thanks for your patience.
